config/routes.rb
Zaytona::Application.routes.draw do
  resources :specifications do
    get :download
  end

  resources :notes
  resources :circuits
  resources :gates

end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  # GET /notes
  # GET /notes.xml
  def index
    @notes = Note.all.group_by(&:category)

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @notes }
    end
  end

  # GET /notes/1
  # GET /notes/1.xml
  def show
    @note = Note.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/new
  # GET /notes/new.xml
  def new
    @note = Note.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @note }
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.xml
  def create
    @note = Note.new(params[:note])

    respond_to do |format|
      if @note.save
        format.html { redirect_to(notes_url, :notice => 'Note was successfully created.') }
        format.xml  { render :xml => @note, :status => :created, :location => @note }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.xml
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to(notes_url, :notice => 'Note was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @note.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.xml
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    respond_to do |format|
      format.html { redirect_to(notes_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.haml
- semantic_form_for @note do |f|
  - f.inputs do
    = f.input :title
    = f.input :category
    = f.input :body, :input_html => {:class => 'wymeditor widest'}
    = f.commit_button 'Update',  :button_html => {:class => 'wymupdate'}

app/views/notes/edit.html.haml
- title "Edit Note"

= render :partial => 'form'

%p
  = link_to "Show", note_path(@note)
  |
  = link_to "View All", notes_path

app/views/notes/index.html.haml
#edit-note
  - title "Notes"
  - @notes.each do |category, notes|
    %ul.collapser
      %li
        =link_to category, '#', :class => 'category'
        %ul
          - notes.each do |note|
            %li
              = link_to note.title, edit_note_url(note)
              .destroy= button_to 'Destroy', note_path(note), :confirm => 'Are you sure?', :method => :delete
.clr
%p= link_to "New Note", new_note_path

app/views/notes/new.html.haml
- title "New Note"

= render :partial => 'form'

%p= link_to "Back to List", notes_path

app/views/notes/show.html.haml
- title "Note"

%p
  %strong Title:
  =h @note.title

%p
  = link_to "Edit", edit_note_path(@note)
  |
  = link_to "Destroy", @note, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", notes_path