config/routes.rb
Zaytona::Application.routes.draw do
  resources :specifications do
    get :download
  end

  resources :notes
  resources :circuits
  resources :gates

end

app/models/circuit.rb
class Circuit < ActiveRecord::Base

  validate :content_format

  def content_format
    g = parsed_content.split(" ")
    raise SyntaxError, "Bit size mismatch" if g.map(&:size).uniq.size > 1
  end

  def self.options_for_format
    ["compact", "netlist (not implemented)"]
  end

  def parsed_content
    @content ||= strip_comments(content)
    invalid = @content.split('').uniq - %w(0 1 + v V x \ )
    raise SyntaxError, "Invalid input found: #{invalid}" unless invalid.empty?
    @content
  end

  def n_bits
    @n_bits ||= parsed_content[:n_bits].to_i rescue 0
  end

  def gates
    return nil unless parsed_content

    g = parsed_content.split(" ")
    raise SyntaxError, "Bit size mismatch" if g.map(&:size).uniq.size > 1
    g
  end

  def file_content=(f)
    if f.present?
      val = f.read
      self[:content] = strip_comments(val)
    end
  end

  def strip_comments(text)
    return nil if text.nil?
    text.split("\n").map(&:strip).map do |line|
      value = line.split('#').first
      value.blank? ? nil : value.strip
    end.compact.join(" ")
  end
end

app/controllers/circuits_controller.rb
class CircuitsController < ApplicationController

  # GET /circuits
  # GET /circuits.xml
  def index
    @circuits = Circuit.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @circuits }
    end
  end


  # GET /circuits/1
  # GET /circuits/1.xml
  def show
    @circuit = Circuit.find(params[:id])

    @gates = @circuit.gates.map do |target|
      helpers.render_term(target)
    end.transpose

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @circuit }
    end
  end

  # GET /circuits/new
  # GET /circuits/new.xml
  def new
    @circuit = Circuit.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @circuit }
    end
  end

  # GET /circuits/1/edit
  def edit
    @circuit = Circuit.find(params[:id])
    @gates = @circuit.gates.map do |target|
      helpers.render_term(target)
    end.transpose
  end

  # POST /circuits
  # POST /circuits.xml
  def create
    @circuit = Circuit.new(params[:circuit])

    respond_to do |format|
      if @circuit.save
        format.html { redirect_to(@circuit, :notice => 'Circuit was successfully created.') }
        format.xml  { render :xml => @circuit, :status => :created, :location => @circuit }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @circuit.errors, :status => :unprocessable_entity }
      end
    end
  rescue Exception => e
    flash[:alert] =  e.message
    render :action => :new
  end

  # PUT /circuits/1
  # PUT /circuits/1.xml
  def update
    @circuit = Circuit.find(params[:id])

    respond_to do |format|
      if @circuit.update_attributes(params[:circuit])
        format.html { redirect_to :action => :edit }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @circuit.errors, :status => :unprocessable_entity }
      end
    end
  rescue Exception => e
    flash[:alert] =  e.message
    render :action => :edit
  end

  # DELETE /circuits/1
  # DELETE /circuits/1.xml
  def destroy
    @circuit = Circuit.find(params[:id])
    @circuit.destroy

    respond_to do |format|
      format.html { redirect_to(circuits_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/circuits_helper.rb
module CircuitsHelper

  def render_term(target, nbits=nil, control=nil)
    if target.is_a? String
      str = target.split('')
      raise ArgumentError, "number of bits are invalid for #{target}" if( nbits and nbits != str.size )

      nbits = str.size
      target = control = 0
      str.each do |char|
        target  <<= 1
        control <<= 1
        target  |= 1 if char == '+'
        control |= 1 if char == '1'
      end
    end

    gates = []
    target_pos = target_position(target)
    left, right = bounding_controls(control, target_pos)

    list = [EMPTY] * nbits

    return list if target == 0

    if control == 0
      list[target_pos] = NOT
      return list.reverse
    end

    (right..left).each do |index|
      combo = (target >> (index-1) & 2) + (control >> (index) & 1)
      list[index] = case combo
        when 0b00: WIRE
        when 0b01:
          case index
            when left: CTRL_BOTTOM
            when right: CTRL_TOP
            else CTRL_BOTH
          end
        when 0b10:
          case index
            when left: NOT_BOTTOM
            when right: NOT_TOP
            else NOT_BOTH
          end
        else INVALID
      end
    end

    list.reverse
  end

  def target_position(target)
    return nil if target == 0
    @bit_array ||= bit_array

    count = 0
    index = nil
    offset = 1

    while target > 0
      word = target & 0xffff
      target >>= 16
      offset += 16
      next if word == 0

      index = @bit_array.index(word) + offset - 16

      count += 1
    end

    raise ArgumentError unless count == 1
    index - 1
  rescue
    raise ArgumentError
  end

  def bit_array
    (0..15).inject([]) {|r,i| r << (1 << i)}
  end

  def bounding_controls(control, target)
    return [0,0] if control == 0

    right = left = nil

    (0..(control.size*8)).each do |index|
      bit = control & 1
      if bit == 1
        left = index
        right = index if right == nil
      end

      control >>= 1
    end

    [ [left, target].max, [target,right].min ]
  end
end

app/views/circuits/_form.html.haml
= form_for @circuit, :html => {:multipart => true} do |f|
  -if @circuit.errors.any?
    #error_explanation
      %h2= "#{pluralize(@circuit.errors.count, "error")} prohibited this circuit from being saved:"
      %ul
        - @circuit.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :format
    = f.select :format, Circuit.options_for_format
  .field.float-left
    = f.label :content
    = f.text_area :content
  .field.help
    %p The following options are supported:
    %p #: Comment line (ignored)
    %p 1: Control line
    %p 0: Not involved
    %p +: NOT gate
    %p x: SWAP gate (not yet implemented)
    %p v: V Gate (not yet implemented)
    %p V: V+ Gate  (not yet implemented)

  .actions.brk
    = f.submit 'Draw Circuit'

    = link_to 'My circuits', circuits_path

- if @gates
  #circuit-graph
    - literal = ("a".ord-1).chr
    - @gates.each do |qubits|
      .row
        %div{:class => :literal}= literal.succ!
        - qubits.each do |qubit|
          %div{:class => GATE_MAP[qubit]}

app/views/circuits/edit.html.haml
%h1 Editing circuit

= render 'form'

app/views/circuits/index.html.haml
%h1 Listing circuits

%table
  %tr
    %th Title
    %th Content
    %th
    %th
    %th

  - @circuits.each do |circuit|
    %tr
      %td= circuit.title
      %td= circuit.content
      %td= link_to 'Show', edit_circuit_path(circuit)

%br

= link_to 'New Circuit', new_circuit_path

app/views/circuits/new.html.haml
%h1 New circuit

= render 'form'

= link_to 'Back', circuits_path

app/views/circuits/show.html.haml
%p
  %b Title:
  = @circuit.title

= link_to 'Edit', edit_circuit_path(@circuit)
\|
= link_to 'Back', circuits_path
- if @gates
  #circuit-graph
    - literal = ("a".ord-1).chr
    - @gates.each do |qubits|
      .row
        %div{:class => :literal}= literal.succ!
        = qubits.each do |qubit|
          %div{:class => GATE_MAP[qubit]}