config/routes.rb
Zaytona::Application.routes.draw do
  resources :specifications do
    get :download
  end

  resources :notes
  resources :circuits
  resources :gates

end

app/models/gate.rb
class Gate < ActiveRecord::Base
end

app/controllers/gates_controller.rb
class GatesController < ApplicationController
  # GET /gates
  # GET /gates.xml
  def index
    @gates = Gate.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @gates }
    end
  end

  # GET /gates/1
  # GET /gates/1.xml
  def show
    @gate = Gate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @gate }
    end
  end

  # GET /gates/new
  # GET /gates/new.xml
  def new
    @gate = Gate.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @gate }
    end
  end

  # GET /gates/1/edit
  def edit
    @gate = Gate.find(params[:id])
  end

  # POST /gates
  # POST /gates.xml
  def create
    @gate = Gate.new(params[:gate])

    respond_to do |format|
      if @gate.save
        format.html { redirect_to(@gate, :notice => 'Gate was successfully created.') }
        format.xml  { render :xml => @gate, :status => :created, :location => @gate }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @gate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /gates/1
  # PUT /gates/1.xml
  def update
    @gate = Gate.find(params[:id])

    respond_to do |format|
      if @gate.update_attributes(params[:gate])
        format.html { redirect_to(@gate, :notice => 'Gate was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @gate.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /gates/1
  # DELETE /gates/1.xml
  def destroy
    @gate = Gate.find(params[:id])
    @gate.destroy

    respond_to do |format|
      format.html { redirect_to(gates_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/gates_helper.rb
module GatesHelper
end

app/views/gates/_form.html.haml
= form_for @gate do |f|
  -if @gate.errors.any?
    #error_explanation
      %h2= "#{pluralize(@gate.errors.count, "error")} prohibited this gate from being saved:"
      %ul
        - @gate.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :image
    = f.text_field :image
  .field
    = f.label :symbol
    = f.text_field :symbol
  .actions
    = f.submit 'Save'

app/views/gates/edit.html.haml
%h1 Editing gate

= render 'form'

= link_to 'Show', @gate
\|
= link_to 'Back', gates_path

app/views/gates/index.html.haml
%h1 Listing gates

%table
  %tr
    %th Name
    %th Image
    %th Symbol
    %th
    %th
    %th

  - @gates.each do |gate|
    %tr
      %td= gate.name
      %td= gate.image
      %td= gate.symbol
      %td= link_to 'Show', gate
      %td= link_to 'Edit', edit_gate_path(gate)
      %td= link_to 'Destroy', gate, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Gate', new_gate_path

app/views/gates/new.html.haml
%h1 New gate

= render 'form'

= link_to 'Back', gates_path

app/views/gates/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @gate.name
%p
  %b Image:
  = @gate.image
%p
  %b Symbol:
  = @gate.symbol

= link_to 'Edit', edit_gate_path(@gate)
\|
= link_to 'Back', gates_path