config/routes.rb
Zaytona::Application.routes.draw do
  resources :specifications do
    get :download
  end

  resources :notes
  resources :circuits
  resources :gates

end

app/models/specification.rb
class Specification < ActiveRecord::Base
  serialize :parameters
  RadixList = [ ["Binary(2)", 2], ["Ternary(3)", 3], ["Quaternary(4)", 4], ["Quinary (5)", 5], ["Senary (6)", 6], ["Septenary (7)", 7]]
  AvailableFunctions = QuFunction::Generators.available_functions.map{|klass| [klass.name, klass.to_s]}
  def self.find_or_initialize_by_parameters(params)
    instance = find_or_initialize_by_name_and_radix_and_variables_and_completed(params[:name], params[:radix], params[:variables], params[:completed])
    instance.parameters = params
    instance.generate
  end

  def generator_class
    name.constantize
  end

  def generate
    return self if content.present?
    options = {:complete => completed}
    self.signature, self.content = QuFunction::Specification.generate(name, parameters[:radix], parameters[:variables], options)
    self
  end

  def human_name
    AvailableFunctions.detect {|x| x.last == name}.first
  end

  def human_radix
    RadixList.detect {|x| x.last == radix }.first
  end
end

app/controllers/specifications_controller.rb
class SpecificationsController < ApplicationController
  # GET /specifications
  # GET /specifications.xml
  def index
    @specifications = Specification.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @specifications }
    end
  end


  def download
    @specification = Specification.find(params[:specification_id])
    send_data(@specification.content, :filename => (@specification.signature + "xqs"))
  end

  # GET /specifications/1
  # GET /specifications/1.xml
  def show
    @specification = Specification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @specification }
    end
  end

  # GET /specifications/new
  # GET /specifications/new.xml
  def new
    @specification = Specification.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @specification }
    end
  end

  # GET /specifications/1/edit
  def edit
    @specification = Specification.find(params[:id])
  end

  # POST /specifications
  # POST /specifications.xml
  def create
    @specification = Specification.find_or_initialize_by_parameters(params[:specification])

    respond_to do |format|
      if @specification.save
        format.html { redirect_to(@specification, :notice => 'Specification was successfully created.') }
        format.xml  { render :xml => @specification, :status => :created, :location => @specification }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @specification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /specifications/1
  # PUT /specifications/1.xml
  def update
    @specification = Specification.find(params[:id])

    respond_to do |format|
      if @specification.update_attributes(params[:specification])
        format.html { redirect_to(@specification, :notice => 'Specification was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @specification.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /specifications/1
  # DELETE /specifications/1.xml
  def destroy
    @specification = Specification.find(params[:id])
    @specification.destroy

    respond_to do |format|
      format.html { redirect_to(specifications_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/specifications_helper.rb
module SpecificationsHelper
end

app/views/specifications/_form.html.haml
= form_for @specification do |f|
  -if @specification.errors.any?
    #error_explanation
      %h2= "#{pluralize(@specification.errors.count, "error")} prohibited this specification from being saved:"
      %ul
        - @specification.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.select :name, Specification::AvailableFunctions 
  .field
    = f.label :radix
    = f.select :radix, Specification::RadixList
  .field
    = f.label :variables
    = f.select :variables, (3..20)
  .field
    = f.label :completed
    = f.check_box :completed
  .actions
    = f.submit 'Generate'

app/views/specifications/edit.html.haml
%h1 Editing specification

= render 'form'

= link_to 'Show', @specification
\|
= link_to 'Back', specifications_path

app/views/specifications/index.html.haml
%h1 Listing specifications

%table.dataTable
  %thead
    %tr
      %th Name
      %th Signature
      %th Radix
      %th Variables
      %th Complete
      %th

  %body
    - @specifications.each do |specification|
      %tr
        %td= specification.human_name
        %td= specification.signature
        %td= specification.human_radix
        %td= specification.variables
        %td= specification.completed
        %td= link_to 'Show', specification

%br

= link_to 'New Specification', new_specification_path

= javascript_tag do
  $(document).ready(function() {
  $('.dataTable').dataTable();
  } );dataTable

app/views/specifications/new.html.haml
%h1 New specification

= render 'form'

= link_to 'Back', specifications_path

app/views/specifications/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @specification.name
%p
  %b Radix:
  = @specification.radix
%p
  %b Variables:
  = @specification.variables
%p
  %b Completed:
  = @specification.completed
%p.specification
  = text_area_tag :specification, @specification.content, :disabled => true

= link_to 'Download XQS file', specification_download_path(@specification)
\|
= link_to 'Specification List', specifications_path